#!/usr/bin/env ruby

require "dshell"

Dshell do
  instructions "Type 'help' for help"

  help :history, "Show the list of commands you've entered so far"
  command :history do
    show_history
  end

  help :ls, "Show the list of commands you've entered so far"
  command :ls do
    puts `ls #{current_dir}`
  end

  help :cat, "Prints out the content of the specified files"
  command :cat do |argv|
    if argv.empty?
      show_error "No file specified"
    else
      #FIXME: This will allow them to break out of the
      # virtual filesystem.
      argv = argv.map do |file|
        [file, real_file_for(Pathname.new(file))]
      end
      argv.each do |name, file|
        if file.exist?
          puts `cat #{file}`
        else
          show_error(
            "#{name}: No such file or directory"
          )
        end
      end
    end
  end

  help :cd, "Change directory"
  command :cd do |argv|
    change_dir argv.join(' ')
  end

  help :pwd, "Prints the current directory"
  command :pwd do |argv|
    puts virtual_file_for current_dir
  end

  help :exit, "Logout of the system"
  command :exit do |argv|
    exit 0
  end

  help :ssh, "Connect to another server"
  command :ssh do |argv|
    if argv.empty?
      show_error "No server specified"
    else
      host = argv.first
      system('ssh', host)
    end
  end

  #add_to_history 'stuff'

end
