#!/usr/bin/env ruby

require "dshell"

Dshell do
  instructions "Type 'help' for help"

  help :history, "Show the list of commands you've entered so far"
  command :history do
    puts history
  end

  help :ls, "Show the list of commands you've entered so far"
  command :ls do |argv|
    help "List files"
    puts "listing for #{argv}"
  end

  help :cd, "Change directory"
  command :cd do |argv|
    help "Change directory"
    change_dir argv.join(' ')
  end

  help :pwd, "Prints the current directory"
  command :pwd do |argv|
    help "Prints the current directory"
    puts virtual_dir_for current_dir
  end

end
